---
- name: Services Configuration
  hosts: all
  gather_facts: false

  collections:
    - cisco.ios

  tasks:
    - name: Configure NTP and Logging Buffer
      ios_config:
        lines:
          - "ntp server time.google.com"
          - "logging buffered 16384"
